Add UpdateWorkerPoolLabels to v2 implementation
IBM-Cloud/bluemix-go pull request #422
Opened 2024-01-03 15:54 UTC by Blintmester

2024-01-04 15:40 UTC, lewiseevans requested changes

2024-01-04 15:40 UTC, lewiseevans commented on api/container/containerv2/worker_pool.go
> +	Lables     map[string]string `json:"labels" description:"Labels to apply to the worker pool and each of its worker nodes."`
```suggestion
	Labels     map[string]string `json:"labels" description:"Labels to apply to the worker pool and each of its worker nodes."`
```

2024-01-04 15:40 UTC, lewiseevans commented on api/container/containerv2/worker_pool.go
> +	Lables     map[string]string `json:"labels" description:"Labels to apply to the worker pool and each of its worker nodes."`
Please re-order this block so we have 

* Cluster
* WorkerPool
* Labels

2024-01-08 13:57 UTC, lewiseevans requested changes

2024-01-09 12:17 UTC, Blintmester commented on api/container/containerv2/worker_pool.go
> +	WorkerPool string            `json:"workerpool" description:"worker Pool name"`
done

2024-01-09 12:48 UTC, lewiseevans approved these changes

2024-01-10 13:20 UTC, merged